apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    k8s-app: elasticsearch-exporter
  name: elasticsearch-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 9108
    protocol: TCP
  selector:
    k8s-app: elasticsearch-exporter
